name: Build & Deploy Jaspr to cPanel

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  build-deploy:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.12.0"


      - name: Install Jaspr CLI
        run: |
          dart pub global activate jaspr_cli 0.23.1
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH


      - name: Check deffcon folder
        run: |
          ls -la
          ls -la deffcon
          cat deffcon/pubspec.yaml


      - name: Get dependencies
        working-directory: deffcon
        run: dart pub get


      - name: Build Jaspr
        working-directory: deffcon
        run: jaspr build

      - name: Inspect build output
        working-directory: deffcon
        run: |
          echo "Current directory:"
          pwd

          echo "Build directory:"
          ls -la build || true

          echo "Build/jaspr:"
          ls -la build/jaspr || true

          echo "Find index.html:"
          find build -name index.html || true

          echo "Find main.dart.js:"
          find build -name "*.js" || true